import { parseAbi } from "viem";

export const baseKudosAbi = parseAbi([
  "constructor(string initialURI)",
  "event ApprovalForAll(address indexed account,address indexed operator,bool approved)",
  "event KudosSent(uint256 indexed kudosId,address indexed sender,address indexed receiver,uint256 cardType,string message,uint256 timestamp,address referrer)",
  "event OwnershipTransferred(address indexed oldOwner,address indexed newOwner)",
  "event PointsUpdated(uint256 senderPoints,uint256 receiverPoints,uint256 referrerBonus,uint256 userBonus)",
  "event TransferBatch(address indexed operator,address indexed from,address indexed to,uint256[] ids,uint256[] values)",
  "event TransferSingle(address indexed operator,address indexed from,address indexed to,uint256 id,uint256 value)",
  "event URI(string value,uint256 indexed id)",
  "function CARD_TYPES() view returns (uint256)",
  "function MAX_MESSAGE_LENGTH() view returns (uint256)",
  "function balanceOf(address account,uint256 id) view returns (uint256)",
  "function balanceOfBatch(address[] accounts,uint256[] ids) view returns (uint256[])",
  "function getKudos(uint256 kudosId) view returns ((address sender,address receiver,uint256 cardType,string message,uint256 timestamp))",
  "function getUser(address user) view returns ((uint256 sentCount,uint256 receivedCount,uint256 rewardPoints,address referralOf))",
  "function isApprovedForAll(address account,address operator) view returns (bool)",
  "function owner() view returns (address)",
  "function receiverPoints() view returns (uint256)",
  "function referrerBonus() view returns (uint256)",
  "function safeBatchTransferFrom(address from,address to,uint256[] ids,uint256[] values,bytes data)",
  "function safeTransferFrom(address from,address to,uint256 id,uint256 value,bytes data)",
  "function sendKudos(address receiver,uint256 cardType,string message,address referrer)",
  "function senderPoints() view returns (uint256)",
  "function setApprovalForAll(address operator,bool approved)",
  "function setPoints(uint256 _senderPoints,uint256 _receiverPoints,uint256 _referrerBonus,uint256 _userBonus)",
  "function setURI(string newURI)",
  "function supportsInterface(bytes4 interfaceId) pure returns (bool)",
  "function totalKudos() view returns (uint256)",
  "function transferOwnership(address newOwner)",
  "function uri(uint256) view returns (string)",
  "function userBonus() view returns (uint256)"
] as const);
